enum PassengerState {
    WALKING_TO_TICKET,
    WAITING_FOR_TICKET,
    BUYING_TICKET,
    WALKING_TO_PLATFORM,
    WAITING_ON_PLATFORM,
    MOVING_TO_BAY_LINE,
    WAITING_IN_BAY_LINE,
    WALKING_TO_BUS,
    SEATED_IN_BUS
}
